services:
    db:
      image: postgres:17-alpine
    env_file:
        - .env
    volumes:
        - postgresDB:/Users/elena/Documents/GitHub/elmafo99
    ports:
        - "5433:5432"
    restart: unless-stopped

volumes:
        postgresDB: